# Generated by Django 5.0.1 on 2025-05-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.AddField(
            model_name='ticket',
            name='destinate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_destination', to='ticketbooking.train'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_origin', to='ticketbooking.train'),
        ),
    ]
