# Generated by Django 5.0.1 on 2025-05-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0002_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
