# Generated by Django 5.0.1 on 2025-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0002_remove_ticket_destination_ticket_destinate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='departuretimedate',
            field=models.DateTimeField(default='12:20'),
        ),
    ]
