# Generated by Django 5.0.1 on 2025-05-12 15:52

import ticketbooking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0002_ticket_name_alter_train_seat_info_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pnr_number',
            field=models.CharField(db_index=True, default=ticketbooking.models.generate_pnr, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
    ]
