# Generated by Django 5.0.1 on 2025-05-12 18:19

import django.contrib.postgres.fields
import ticketbooking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0003_alter_ticket_pnr_number_alter_train_available_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pnr_number',
            field=models.CharField(db_index=True, default=ticketbooking.models.generate_pnr, max_length=8),
        ),
        migrations.AlterField(
            model_name='train',
            name='seat_info_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
