# Generated by Django 5.0.1 on 2025-05-09 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0006_alter_train_arrivaldatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrivaldatetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 13, 55, 23, 569854)),
        ),
        migrations.AlterField(
            model_name='train',
            name='departuretimedate',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 9, 13, 55, 23, 569854)),
        ),
    ]
