# Generated by Django 5.0.1 on 2025-05-09 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0009_alter_train_arrivaldatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='arrivaldatetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='train',
            name='departuretimedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
